server:
  port: 8081

spring:
  # mysql
  datasource:
    url: jdbc:mysql://localhost:3308/adgile?useSSL=false
    username: root
    password: 1234

  jpa:
    open-in-view: false
    defer-datasource-initialization: false
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  ## swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

## logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG



