server:
  port: 8081

spring:
  # mysql
  datasource:
    url: jdbc:mysql://localhost:3308/adgile?useSSL=false
    username: root
    password: 1234

  jpa:
    open-in-view: false
    defer-datasource-initialization: false
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  ## swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

## logging
logging:
  config: classpath:logback-local.xml
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              org.hibernate.type.descriptor.sql.BasicBinder: TRACE

## cloud
cloud:
  aws:
    credentials:
      secret-key: { { accesskey } }
      access-key:  { { secret-key } }
    sqs:
      queue:
        name: { { name } }
        url: https://sqs.ap-northeast-2.amazonaws.com/122312/{{name}}

