### 조회
GET {{local}}/v1/member/1
Content-Type: application/json

### 리스트
GET http://{{local}}/v1/member
Content-Type: application/json

### id check
GET {{local}}/v1/member/check/doyeon1123
Content-Type: application/json

### 생성
POST {{local}}/v1/member
Content-Type: application/json

{
  "isDomestic": true,
  "type":  0,
  "userType": 1,
  "memberId" : "1234",
  "name" : "도연111112",
  "manager" : "과장",
  "email" : "doyeon@test.com",
  "invoiceEmail" :  "doyeon@test.com",
  "currencyType": 1
}

### 수정
PUT {{local}}/v1/member/1
Content-Type: application/json

{
  "isDomestic": false,
  "type": 1,
  "userType": 1,
  "memberId" : "doyeon12",
  "name" : "도연",
  "manager" : "대리",
  "email" : "doyeon@shallwead.com",
  "invoiceEmail" :  "doyeon@shallwead.com",
  "currencyType": 1
}

### 삭제
DELETE {{local}}/v1/member/1
Content-Type: application/json
